### ISSUE TITLE
Removing previously dlded shows

### ISSUE THREAD

**Issue by crashtestoz** [mipstian/catch#117]
How do I remove previously downloaded shows from the list? I am try to get Catch to re-download and nothing is happening when I click the refresh button to the right of a recently downloaded show.

Should magnet links be saving in my Watch folder?

I am using new RSSSHOW and Catch 1.9.3

**Comment by mipstian** [comment]
What I'm hearing you say is you'd like the refresh button to work properly :)

When you click that, if the item you're trying to re-download was a magnet link, Catch just tells OSX to open that magnet link. This should result in your default .torrent handler app to be launched. The app will then save the torrent's contents in **it's** default download folder, because Catch can't tell it where to save stuff through a magnet link. Note that the link is opened "in the background", so your torrent client's window might appear below some other open window.

What torrent client do you use? If it's Transmission make sure to update to the latest version (2.92).

**Comment by crashtestoz** [comment]
I'm using Transmission for QNAP so I am relying on Catch saving files to a watch folder. Magen links will not work. I noticed however that with maglinks option set to false, sometimes the Catch can not download the files and reports a error.

**Comment by mipstian** [comment]
Yeah if you need torrent files to be downloaded on another machine, magnets are not an option. You might be interested in #111, coming with the next version. I'd love some feedback on how to better accommodate the kind of setup you have.
