### ISSUE TITLE
Clear "Recent Episodes" list

### ISSUE THREAD

**Issue by Seacidal** [mipstian/catch#119]
Hi! I'm running Catch v1.93 and I love it! It's great! Thanks! I do have one minor suggestion/request. Would it be possible somehow to "clear" the "Recent Episodes" list? It's not that big of a deal, but it would be nice to be able to clear it once in awhile. Thanks.

Make sure to do the following before submitting your issue - thanks!

- [x] Make sure you're running the [latest release](https://github.com/mipstian/catch/releases/latest). You can find your version number at the bottom of the Help menu in Catch.
- [x] [Check the FAQ](https://github.com/mipstian/catch/wiki/Frequently-Asked-Questions), your question might be answered there.
- [x] [Check for an open issue](https://github.com/mipstian/catch/issues), and please comment on that issue instead of creating a duplicate.

**Comment by mipstian** [comment]
Hmm, I don't think that's a great idea. You seem to interpret that screen as a notification list, like the items aren't needed anymore once you've read them. In this case, I'd turn on notifications and use Notification Center to clear them.

Additionally, that list is already limited in size, so it's not like it's gonna grow forever and cause issues.

If this is a "visual clutter" thing, like when people kill iOS apps just because they don't wanna see them in the task switcher, then I'd rather not encourage that behavior.

Closing for now. But feel free to make your case for it, I might be missing something! You didn't quite state why you want to clear the list.

**Comment by Seacidal** [comment]
No need to reopen. You mentioned the list is already limited in size. That was my primary concern. My secondary concern is privacy, but Catch is the least of my concerns on that point. Thanks for your explanation. I truly enjoy Catch and all your efforts and time spent working on it. Thank you.

**Comment by mipstian** [comment]
Yeah, I figured privacy wouldn't be a big deal since all of the feeds are public already. Glad you're enjoying Catch!

**Comment by mipstian** [comment]
For future reference, Catch's history can be nuked with this command:
`defaults delete org.giorgiocalderolla.Catch history`
No need to close Catch.

On the next check, Catch will of course start downloading everything that's in the feed and repopulate the history, but only for shows that are still in the feed.
