### ISSUE TITLE
Support removable storage

### ISSUE THREAD

**Issue by zenspider** [mipstian/catch#127]
My console is full of this and I've not been getting any of my feed for days:

10/10/16 17:11:29.537 com.giorgiocalderolla.Catch.CatchFeedHelper[23970]: Could not download http://reflektor.karmorra.info/torrent/ED01562FC20BF203BDDE461FD80EC3FF7843390C.torrent: Error Domain=com.giorgiocalderolla.Catch.CatchFeedHelper Code=-7 "Could not download file (bad status code 404)" UserInfo={NSLocalizedDescription=Could not download file (bad status code 404)}

I switched my feed to magnet links and 20-ish things showed up immediately... BUT:

Magnets aren't a good solution to this problem, as my data is all on an external disk and not always plugged in to my laptop. Firing up Transmission without that disk winds up pausing all of the existing torrents (which need to be manually resumed) and then new torrent tries to write to a disk path that doesn't exist, and corrupts.

Further, webloc files aren't recognized by Transmission, so disabling the "Open automatically" preference just seems to break things further.

Is it possible to have multiple sources to check?

OR, is it possible to have a setting that only checks if a path exists? (I'm starting to like this one)

OR, am I missing something?

**Comment by mipstian** [comment]
So couple things:

1) webloc files work fine with Transmission, in the sense that double-clicking one will open Transmission and start downloading.
2) What do you mean by "multiple sources"?
3) Catch should already skip checking if the output folder is invalid. It checks for its existence and writability, before even attempting to check the feed. https://github.com/mipstian/catch/blob/master/CTCScheduler.m#L125

**Comment by zenspider** [comment]
For whatever reason, github was down for the PNW last night.... I'm back:

1) webloc files might open in transmission, but they don't get picked up via the directory scanning mechanism... double-clicking _one_ might be fine... but what about twenty? Bad workflow.
2) This might be from showrss, not from catch... but I was hoping there could be multiple sources for the torrent files so if one goes wonky, you have a backup plan.
3) I don't want Catch to check the output folder (well, I do, but that's not what I'm requesting). I want to be able to specify my _transmission_ download folder, and not have catch check until that path exists (ie, transmission can start up and start downloading w/o errors).

The more I think about it the more I really like 3. I haven't coded on an OSX project in a long time, but I could take a rough stab at it to get the idea across.

**Comment by mipstian** [comment]
1) Open automatically exists precisely to avoid launching stuff manually! Saving files and using some dir scanning is no substitute.
2) ShowRSS yeah, and afaik it's not so much an issue of finding the sources, it's they just don't exist because .torrent files are problematic.
3) There's no way that I know of to tell Transmission where to download. Not to mention Catch is supposed to work with any torrent client.

So, why not just set Catch's output folder to the external drive and use Open automatically?

**Comment by zenspider** [comment]
1) I don't know what you mean by "Saving files and using some dir scanning is no substitute". As I said originally, open automatically is problematic. I'm in my cafe right now. I don't have my external disk attached, and Catch just fired off a magnet, opened Transmission, and invalidated all the missing torrents. Had I left it open, it would have tried to download the magnet file to a path that doesn't exist and corrupted after writing the first block.

3) Totally possible, see https://transmissionbt.com/help/gtk/2.3x/html/preferences.html#downloading 

Further, This isn't about Transmission. Regardless of whatever client I'm using, I'm going to be using an external disk. I just want catch to be smarter so that if, for example, "/Volumes/Media" isn't mounted, then it shouldn't check for torrents yet. The path is arbitrary. It is no different than the time restrictions for Catch.

I hadn't thought of setting Catch to output to the external drive. Right now it goes to my downloads folder, which fits my mental model of the pipeline that I'm working through (web -> Downloads -> Transmission -> torrents folder -> process folder -> file or watch).

I still think this would be a good feature addition. Do you not?

**Comment by mipstian** [comment]
I know you can set Transmission's download folder in its preferences, I meant it can't be done programmatically. As far as I know, you can't pass a .torrent file or magnet link to Transmission and tell it where to download its contents.

I don't think this feature would make sense as it's just a redundant and more roundabout way of using the app as intended. Meaning: using magnet links, open automatically, and setting your download folder to where you want stuff to be downloaded to.

I think the wording in Catch could be improved though. When the last update fails, we should have a reason for the failure in the UI. And in a case like this, it should probably say "skipped" instead of "failed", and mention that the download folder isn't available as a reason for skipping.

Additionally, the app currently pops up its configuration panel on launch if the download folder is invalid, which doesn't perfectly support your use case.

**Comment by zenspider** [comment]
Your first two paragraphs make me think that we're talking past each other.

I agree that it would be nice if Catch would differentiate between skipping and actually invalid updates. That would be nice. In my case, I think they were actually invalid updates (when I was fetching real torrent files).

> Additionally, the app currently pops up its configuration panel on launch if the download folder is invalid, which doesn't perfectly support your use case.

Where "doesn't perfectly support" means "totally messes up"? If I'm understanding correctly, you are suggesting a workaround to my feature request to set up Catch to save to the external disk, as opposed to the default Downloads folder, even tho I'm using magnets, so it won't check until the disk is available... but if the disk isn't there when catch starts up (which it NEVER is), it'll bring up its preferences every time. Is that a correct understanding? That's an anti-workflow if ever I heard of one.

Versus: add a preference to Catch to allow users to specify where their torrents actually are (not where the torrent files to be fed to their clients are downloaded) and add 1 extra boolean check next to the time range checker to see if the directory currently exists.

**Comment by mipstian** [comment]
So what I hear you saying is the only problem you see with my solution is that the dialog pops up (please correct me if I'm wrong). That is _really_ easy to change. Way easier than to add a new setting – not that that's hard, it's just hard by comparison. Most importantly though, having another setting is way more consequential.

Also to clarify, the dialog would pop up when Catch launches (which generally happens at login), not when it checks every 10m. In my personal use, that translates to about once a month. The problem is more that currently, an unreachable path is considered "invalid configuration", so the app won't accept it. We should change that logic so invalid paths don't invalidate the whole configuration, and specifically check for invalid paths (on top of the configuration validity) before checking the feed. That's a two-line change.

Torrent files are on their way out: they are almost unfeasible today with ShowRSS, and it's not gonna get any better. Even if you had the setting as you described, you would still get 404s. So we gotta make magnets work.

I think it's reasonable to have Catch skip checks when the download folder is unavailable, whether it's used to write torrent files or not. We could even have the UI say "Catch will skip checking if this location becomes unavailable" next to the setting.

**Comment by zenspider** [comment]
Having just travelled for 2 weeks I gotta say... The current setup **sucks**.

I feel even more strongly that the feature I'm suggesting is the right way to go. NOT checking and NOT opening magnets unless an destination of interest is available is the right thing for the average user. This has nothing to do with transmission and everything to do with Catch not playing well with others.

I'm not in a position to do this PR (no xcode, been years)... but I can take a first stab at it if that helps relieve pressure.

**Comment by mipstian** [comment]
That (skipping checks when the folder isn't available) is what I've proposed as well. The difference between our proposals is that you want to have two different settings, one for where to download the .torrent files to, and one where to download their contents to. I just want to use the existing setting. Because .torrent files are unviable as it is and I'm being told it's not gonna get any better, having two settings doesn't make sense to me. In a magnet-only world there are no .torrent files. At best, we might be able to tell the torrent client to output to the folder chosen in Catch.

How does having two folder settings help?

No need to PR, in fact I was gonna make this change and upload an alpha build so anybody can try it out. The enhanced messaging (i.e. "Check skipped because download folder isn't available" or similar) will come later, but there will be a message in Console. Sounds good?

**Comment by mipstian** [comment]
@zenspider try this alpha and let me know how it goes, I think it'll suit your use case: https://github.com/mipstian/catch/releases/tag/2.0-alpha1
