### ISSUE TITLE
Filter results before saving

### ISSUE THREAD

**Issue by smartwatermelon** [mipstian/catch#140]
Version: 1.9.4 (508)
Checked FAQ.
No open issue.

I'd love Catch to implement a filter for retrieved torrents before saving them. This is mostly so I can filter out the AVS/SVA/FLEET trash. I imagine this being a text-matching and/or regex-matching option below the feed URL.

Ideally, ShowRSS would also implement a filter; I've sent them a Tweet requesting it.

Thank you!

**Comment by mipstian** [comment]
I'm not familiar with this "trash" you mentioned, can you better describe it?

**Comment by smartwatermelon** [comment]
Those three release groups tend to abruptly cut episodes before completion, and are reported to use questionable compression methods.

Probably better for the request to simply be, I'd love to be able to filter feed results on text or regex before saving the torrent file.

**Comment by mipstian** [comment]
Hmmm, I see the problem but I disagree with the solution. As far as I know, the responsibility of putting out good torrents falls on showrss. They put out "proper" versions of broken episodes for that reason. Having a client-side filter seems overkill and useless for the vast majority of users.

Since you can even name the bad apples, having them excluded from showrss seems like a far superior solution: one that would work for other clients, puts no burden on users, and is significantly simpler to implement. Send 'em a link to this issue to save time :)

**Comment by smartwatermelon** [comment]
👍🏻
