### ISSUE TITLE
Catch preventing sleep?

### ISSUE THREAD

**Issue by nomoreme** [mipstian/catch#24]
Hi,

is it possible that Catch prevents MacOS to go to sleep automatically after idle time?

running "pmset -g assertions" in terminal.app I get:

```
Assertion status system-wide:
   BackgroundTask                 0
   PreventDiskIdle                0
   ApplePushServiceTask           0
   UserIsActive                   1
   PreventUserIdleDisplaySleep    0
   InteractivePushServiceTask     0
   PreventSystemSleep             0
   ExternalMedia                  0
   PreventUserIdleSystemSleep     1
   NetworkClientActive            0
Listed by owning process:
   pid 48(hidd): [0x0000000a00000f41] 00:10:00 UserIsActive named: "com.apple.iohideventsystem.queue.tickle" 
	Timeout will fire in 297 secs Action=TimeoutActionRelease
   pid 18119(Catch): [0x0000000100000f6c] 00:00:16 PreventUserIdleSystemSleep named: "Background checking is the whole point of the app" 
No kernel assertions.
```

If it's true, there's a way to add an option in Catch to let the Mac goes to sleep and do the RSS check automatically at the wake up?

**Comment by cmd-option** [comment]
Certainly App Nap would defeat the purpose of the app, but preventing the Mac from sleeping seems overkill. Why not just disable App Nap, i.e.

    beginActivityWithOptions:NSActivityBackground|NSActivitySuddenTerminationDisabled

instead of

    beginActivityWithOptions:NSActivityIdleSystemSleepDisabled|NSActivitySuddenTerminationDisabled

**Comment by mipstian** [comment]
@cmd-option will that wake up the mac when Catch needs to check and then go back to sleep? Also, could you test that out? I'm currently running betas everywhere :/

**Comment by cmd-option** [comment]
No, no public API will schedule the wakeup of a sleeping Mac... Is that the idea? I thought App Nap was a problem, not system sleep. Did you mix up the naming?

In that case, I'll retract my previous statement. System sleep doesn't defeat the purpose of the app, at all. It's still running in the background while I'm already using my Mac, I don't need it to run 24h.

I've been using that change for a few weeks now, because my battery kept running down. Works great (for the way I'm using Catch).

**Comment by mipstian** [comment]
Got it, thanks for your help.

So in my personal use case, allowing a Mac to sleep while Catch is open and not paused would render Catch next to useless. The idea is to have stuff already downloaded by the time I wake up/walk up to my Mac, which would never happen if system sleep is allowed. I still get all-day battery life.

On top of that, as I mentioned above, it'll be quite mysterious to other users why Catch would stop working after a while.

I do recognize your use case though. So in conclusion...

I think we need a user-visible setting for this (that switches between the current beginActivity options and the set proposed by @cmd-option) and I think it should be on by default. Which come to think of it, is exactly how Transmission works:
<img width="446" alt="screen shot 2015-07-12 at 5 44 44 pm" src="https://cloud.githubusercontent.com/assets/421341/8638503/bae554fc-28bd-11e5-8468-1aa7e819f646.png">

Sounds good?

**Comment by cmd-option** [comment]
Hmm. I would have thought you'd just disable system sleep in the Energy Saver settings if you don't want the Mac to sleep ever.

So personally, I'd think that option isn't needed and the default should be to allow sleep. :) But its your app, obviously, and I'd really appreciate at least the option. I found the current behavior somewhat surprising. (In Transmission, you'd still want the Mac to sleep after transfers are done, so that option serves as a compromise that can't be configured in the system settings.)

**Comment by mipstian** [comment]
It's not "ever". You can manually quit or pause Catch, and that will allow sleep. You can also schedule Catch to only check at some intervals, so it will automatically pause itself. In all of these scenarios, sleep will be allowed.

Which come to think of it, is a big problem. This might be a contrived example, but: assume I set up Catch to automatically check only at night. The night ends and Catch pauses itself. The system goes to sleep. When the next night comes, if the Mac is still sleeping, Catch can't check the feed. And we're back to square 1 and users asking me why Catch "stops working after a while".

Maybe we need to make the distinction between manual pause and scheduled pause. A manual pause needs a manual resume before Catch can check, so it's fine to allow sleep in that case. A scheduled pause should not allow sleep unless the user has explicitly unchecked the aforementioned future checkbox, which translates to "let my Mac sleep even if it breaks Catch".

**Comment by gnfpt** [comment]
Can you add a setting to allow catch to search on boot and then pause automatically?
Thanks

**Comment by mipstian** [comment]
@gnfpt that should probably be a separate issue. Also make sure to clarify what you mean by "on boot"

**Comment by ledge74** [comment]
I think that preventing sleep on a laptop is really extreme, especially on laptops. Could you add an option to not prevent sleep? So that catch can check the feed while the laptop is in use and just go to sleep (and save battery) when the laptop is not in use?

**Comment by studiosciences** [comment]
Perhaps we could only prevent sleep if the system is connected to power.

**Comment by mipstian** [comment]
@gnfpt please open a separate issue for that.

@studiosciences you might be on to something there. Maybe we can do this without adding a setting. Let me think out loud:
- mac plugged: catch prevents sleeps and fetches
- mac unplugged, in use: catch does not prevent sleep but can still fetch
- mac unplugged, idle: system goes to sleep, catch doesn't fetch
So if Catch can get notifications for this stuff (which it probably can), we can dynamically adjust our power assertions accordingly, preserving the behavior where Catch does not prevent sleep when paused, and with no extra setting.
This would both cover my use case, and also probably don't get too many users think Catch is broken.

Does anybody actually want Catch to allow sleep, even if the mac is plugged in?

**Comment by ledge74** [comment]
@mipstian this is an excellent idea to allow sleep only if the mac is unplugged.

**Comment by gnfpt** [comment]
Re: [catch] Catch preventing sleep? (#24)







@gnfpt please open a separate issue for that.
@studiosciences you might be on to something there. Maybe we can do this without adding a setting. Let me think out loud:


mac plugged: catch prevents sleeps and fetches
mac unplugged, in use: catch does not prevent sleep but can still fetch
mac unplugged, idle: system goes to sleep, catch doesn't fetch So if Catch can get notifications for this stuff (which it probably can), we can dynamically adjust our power assertions accordingly, preserving the behavior where Catch does not prevent sleep when paused, and with no extra setting. This would both cover my use case, and also probably don't get too many users think Catch is broken.

Does anybody actually want Catch to allow sleep, even if the mac is plugged in?
—
Reply to this email directly or view it on GitHub.



Yes, me! :D

-- 
Best regards,
Goncalo Farias

Oxymoron: Partially completed.
<mid:mipstian/catch/issues/24/157017028@github.com>

**Comment by 315234** [comment]
I do. I don't think preventing sleep is a reasonable thing to do. That feature is only supposed to be used to prevent sleep during things like video playback or a current download. An app that continuously periodically polls a server should not stop sleep.

I suggest that the correct behaviour is never to prevent sleep. Catch should check for an update after wake from sleep, and check periodically while the computer is awake. If users really want the computer to be awake all night just to poll a server, they can set to never go to sleep in the system settings.

The normal behaviour of macs is that if I stop using my laptop at 95% battery, it will go to sleep and in the morning it will still have 94% battery. With Catch running, I wake up to find my battery completely drained. I don't think users should have to start thinking about quitting a menubar app just to have reasonable power saving behaviour.

**Comment by studiosciences** [comment]
After considering @315234's comments, I have to agree.

If you are trying to set up a dedicated media center or server, it shouldn't be Catch's responsibility to disable sleep. There are more critical applications for a media server, such as Plex Server, that don't disable sleep. Mac's already have an option to disable sleep, which I already have set on my media server.

I recommend simply removing this behavior.

**Comment by mipstian** [comment]
Thinking out loud:

I too agree that users shouldn't be forced to prevent sleep when Catch is running. And since I run Catch all the time, and the app is almost useless to me with automatic system sleep enabled, I could address my own use case by disabling system sleep at the OS level.

But while there are a few people here that dislike the current behavior, I'm pretty sure there are many more out there that will complain if we change it. The main idea behind Catch is that it *automates* the download of episodes. If I have to wake up my Mac manually do have Catch check, that breaks the fundamental purpose of the app, and I would sympathize with anybody complaining about that.

Of course most of these users could also serve their use case by disabling sleep at the OS level, but I/we'd still have to eat the support cost forever.

I think at this point we have two choices:

1) Add a "Prevent my Mac from sleeping" checkbox

- Make the default value ON, so the app doesn't break unless the user wants it to
- Account for scheduled pauses vs. manual pauses as discussed above
- This requires a non-trivial code change

2) Always enable system sleep in the way @cmd-option suggests, and prevent the support avalanche

-  Intercept users clicking "Report a problem with Catch" sending them to a faq page (in the Wiki probably) that provides the fix (disabling system sleep altogether). This page will contain a link to file an issue.
- Explain this fix in the Configuration page of the Wiki, so new users are aware of it
- Explain and highlight this in the release notes, so existing users are aware (assuming anyone reads those)
- Possibly even leave an open issue in GH, although this sucks :/
- This requires two trivial code changes, and some light documentation work


Now that I've spelled the options out, I'm leaning towards 2. The support problem can hopefully be solved or at least mitigated a lot, and it's less code to maintain (and less work overall).

Question: how did you guys get here? Did you use the menu or went straight to GH?

**Comment by 315234** [comment]
I think option 1 (with default on) has several advantages:

* No behaviour change that would cause complaints
* The option is pretty much self documenting, so there would be no need to educate new or old users about it
* It is explicit about what the behaviour is, so it is much simpler conceptually; the user doesn't have to learn about all the different plugged/unplugged/paused/unpaused states to figure out what Catch is doing
* Most people probably won't go looking for a wiki for something like this (I wasn't even aware of one)

I'm surprised that you think option 1 would be a non-trivial code change.

My own use case is the same as that of @cmd-option. I don't need catch running all night, it finds new shows during the day which is fine. I would be surprised if the user backlash was as strong as you expect, as I suspect this is the more typical use case. I am obviously biased though. I don't really have an opinion on the "paused" option, as I don't understand the advantage of pausing Catch rather than just quitting. I just treat it as "set it and forget it".

As for how I got here, I came straight to the issues page on GitHub.

**Comment by mipstian** [comment]
I think the rationale for pausing is just to have a visual indicator the Catch is there waiting, so you don't forget to re-launch it later. Similar to why scheduled pausing was introduced, but for when there's no predictable schedule.

It's not a trivial code change because we don't have the code, we don't know what the repercussions of the change will be exactly, and it adds another dimension of state to the scheduler (which now has to be aware of whether the current pause was manual or scheduled). It also affects the UI and won't localize itself. I'm not saying it's hard either, just not trivial and way more complex than option 2.


I think we all agree that the plugged/unplugged thing is not the way to go, as some users want sleep even if the Mac is plugged in.


I wish I could poll all users, but let's at least poll this thread! So far we have
Option 1: @315234 
Option 2: @mipstian @studiosciences 

Please let me know what camp you fall in and/or if you've changed your mind.

**Comment by mipstian** [comment]
Relevant: GitHub just added issue templates, and I've added one for this repo, and made it ask submitters to read a FAQ page on the wiki. It would be trivial to add a line to the FAQ about the system sleep thing.

**Comment by gnfpt** [comment]
Make it optional. If the option is checked, catch will work as it is now otherwise it will not disable sleep.

**Comment by jbouaziz** [comment]
I've just pushed a pull request about it. It adds a preference that's by default deactivated. If the users chooses to prevent his mac to go to sleep, it will only do so if it is connected to a power source.

I've also added a functionality that prevents the mac to go sleep if the app is currently checking for new shows.

Feel free to accept it or review it! =)

**Comment by mipstian** [comment]
Hi @jbouaziz , thanks so much!

If you read the discussion above though, you'll see we figured out that reacting on the power state was not a good idea, as some users do want their Mac to sleep even if connected to power. Could you take that part out of the PR?

I can take it from there and make it honor scheduled pauses as well.

I'll add your vote to option 1 :)

**Comment by jbouaziz** [comment]
I've taken out any power related code from the PR.

**Comment by gnfpt** [comment]
> we figured out that reacting on the power state was not a good idea, as some users do want their Mac to sleep even if connected to power. Could you take that part out of the PR?
> 

Or make yet another configuration option...

**Comment by mipstian** [comment]
Alternatively we could have it say:
"Prevent my Mac from sleeping"
Followed by a drop down with options:
"Always"
"When connected to a power source"
"Never"

**Comment by mipstian** [comment]
Done on master, I'm gonna upload a prerelease build of 1.9.4 in a moment and post here. Please try it out and let me know if it doesn't work as expected.

Ideally we should localize this new setting, so if you know any languages besides English and Italian, please let me know what "Prevent system sleep when active" translates to and I'll add it in. @leonklingele

**Comment by mipstian** [comment]
1.9.4 RC1 with new setting available here: https://github.com/mipstian/catch/releases/tag/1.9.4rc1

**Comment by 315234** [comment]
Works well for me, thanks!

**Comment by mipstian** [comment]
@315234 thanks for reporting!

**Comment by mipstian** [comment]
@bytepl if you have a minute, could you update your translation with the new string "Prevent system sleep when active"?
