### ISSUE TITLE
How frequently does catch pull down new episodes?

### ISSUE THREAD

**Issue by consumedsoul** [mipstian/catch#59]
I can't see any settings that shows how frequent catch checks for new episodes, nor is it in any documentation I can find.

Thanks!

**Comment by mipstian** [comment]
Hi!

That's undocumented by design :) For two reasons mainly: users shouldn't have to care if we do our job right, and we can change that value with no advertising in case @adrinavarro thinks we're hitting the servers too hard.

Anyway, it's currently every 10 minutes. You can find the value defined here: https://github.com/mipstian/catch/blob/master/CTCDefaults.m#L7
And even if we change it, it'll still be in the "defaults" code.

**Comment by consumedsoul** [comment]
Ok thanks!  gtk


*Hun Kim* | GH Kim Photography <http://ghkim.com>

[image: Instagram] <http://instagram.com/hunkim>   [image: Facebook]
<http://facebook.com/ghkimphotography>   [image: Twitter]
<http://twitter.com/hunkim>   [image: RSS]
<http://feeds.feedburner.com/ghkim>   [image: Subscribe]
<http://ghkim.com/subscribe>
